# file: C:\Users\rcasa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\plotly\validators\scatter\__init__.py
# hypothesis_version: 6.135.17

['._dx.DxValidator', '._dy.DyValidator', '._fill.FillValidator', '._ids.IdsValidator', '._line.LineValidator', '._meta.MetaValidator', '._mode.ModeValidator', '._name.NameValidator', '._text.TextValidator', '._uid.UidValidator', '._x.XValidator', '._x0.X0Validator', '._xsrc.XsrcValidator', '._y.YValidator', '._y0.Y0Validator', '._ysrc.YsrcValidator']